/// Firebase project configuration constants.
/// The actual sensitive values are injected at build time via --dart-define
/// or loaded from firebase_options.dart (generated by FlutterFire CLI).
class FirebaseConstants {
  FirebaseConstants._();

  static const String projectId = 'kevin-yancy-ai';
  static const String authDomain = 'kevin-yancy-ai.firebaseapp.com';
  static const String storageBucket = 'kevin-yancy-ai.firebasestorage.app';
  static const String messagingSenderId = '1059866072416';
  static const String appId = '1:1059866072416:web:d2d07cd30d3b5aea3b7a05';
  static const String apiKey = 'AIzaSyCeWfVefIX2XL3OIu5coKlJ00xD1SvE0P8';
}

/// Cloud Function names (must match exports in functions/src/index.ts)
class FunctionNames {
  FunctionNames._();

  static const String chat = 'chat';
  static const String addMemory = 'addMemory';
  static const String inviteUser = 'inviteUser';
  static const String updateUserRole = 'updateUserRole';
  static const String acceptInvite = 'acceptInvite';
}

/// Firestore collection names
class Collections {
  Collections._();

  static const String users = 'users';
  static const String memories = 'memories';
  static const String conversations = 'conversations';
  static const String invites = 'invites';
}

/// Storage path prefixes
class StoragePaths {
  StoragePaths._();

  static const String photos = 'photos/';
  static const String voices = 'voices/';
  static const String uploads = 'uploads/';
  static const String tts = 'voices/tts/';
}

/// Memory types
class MemoryType {
  MemoryType._();

  static const String journal = 'journal';
  static const String qa = 'qa';
  static const String photo = 'photo';
  static const String voice = 'voice';
}

/// User roles (must match custom claims in Cloud Functions)
class UserRole {
  UserRole._();

  static const String admin = 'admin';
  static const String delegate = 'delegate';
  static const String family = 'family';
}

/// App-wide string constants
class AppStrings {
  AppStrings._();

  static const String appName = 'Kevin';
  static const String appTagline = 'Always with us.';
  static const String chatHint = 'Say something to Kevin...';
  static const String loginWelcome = 'Welcome back.';
  static const String loginSubtitle = 'Sign in to talk with Kevin.';
}
